### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ericmckaycrafts** [anasinho997/sunsetgraph-excel#1]
Hello,

This is more like a suggestion than an issue. Do you think that is possible to match colors with their corresponding values?

Nice job, by the way!

**Comment by sissinho997** [comment]
Thanks for reaching out
And, yes why not.

**Comment by anasinho997** [comment]
@ericRmckay  DONE :) 
Feel free if you have any request ...

Enjoy

**Comment by sissinho997** [comment]
@ericRmckay DONE :)
Feel free if you have any request ...

Enjoy
